name: Detekt

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: detekt
        run: ./gradlew detekt

      - name: reviewdog
        if: ${{ always() }}
        run: reviewdog -f=checkstyle -name="detekt" -reporter=github-pr-check < ./build/reports/detekt/detekt.xml