name: Static code analysis

on:
  push:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: detekt
        uses: alaegin/Detekt-Action@v1.22.0
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}

#      - name: reviewdog report
#        if: failure()
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}
#        run: |
#          cat ./build/reports/detekt/detekt.xml
#          reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review" -level="warning" <./build/reports/detekt/detekt.xml
